version: '3.8'

volumes:
  postgres_data:
  staticfiles:
  mediafiles:

services:
  db_foodgram:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
      
  web:
    image: rogulin/foodgram:latest
    restart: always
    volumes:
       - staticfiles:/code/static
       - mediafiles:/code/media
    env_file:
      - ./.env
    depends_on:
      - db_foodgram
    container_name: web

  nginx:
    image: nginx:1.19
    restart: always
    ports:
      - "80:80"
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - web
    container_name: nginx
